// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"
	data "goverage/data"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// GetRecentCoverage provides a mock function with given fields: ctx, params
func (_m *Repository) GetRecentCoverage(ctx context.Context, params data.GetRecentCoverageParams) (data.Coverage, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentCoverage")
	}

	var r0 data.Coverage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, data.GetRecentCoverageParams) (data.Coverage, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, data.GetRecentCoverageParams) data.Coverage); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(data.Coverage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, data.GetRecentCoverageParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetRecentCoverage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecentCoverage'
type Repository_GetRecentCoverage_Call struct {
	*mock.Call
}

// GetRecentCoverage is a helper method to define mock.On call
//   - ctx context.Context
//   - params data.GetRecentCoverageParams
func (_e *Repository_Expecter) GetRecentCoverage(ctx interface{}, params interface{}) *Repository_GetRecentCoverage_Call {
	return &Repository_GetRecentCoverage_Call{Call: _e.mock.On("GetRecentCoverage", ctx, params)}
}

func (_c *Repository_GetRecentCoverage_Call) Run(run func(ctx context.Context, params data.GetRecentCoverageParams)) *Repository_GetRecentCoverage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(data.GetRecentCoverageParams))
	})
	return _c
}

func (_c *Repository_GetRecentCoverage_Call) Return(_a0 data.Coverage, _a1 error) *Repository_GetRecentCoverage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetRecentCoverage_Call) RunAndReturn(run func(context.Context, data.GetRecentCoverageParams) (data.Coverage, error)) *Repository_GetRecentCoverage_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
