// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package data

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Coverage struct {
	ID           int32
	RepoName     string
	ProjectName  string
	BranchName   string
	Commit       string
	Coverage     float64
	CoverageDate pgtype.Timestamptz
	RawData      []byte
}
